language: java

jdk:
  - openjdk11

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../src

script:

  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install -P test-consumer,test-business sonar:sonar -Dsonar.login=a1c09338c829e60db8a141c686207d664eeba0c9
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
  - cd ../../src


notifications:
  email: false

addons:
  sonarcloud:
    organization: "nicoevgl"
    token:
      secure: a1c09338c829e60db8a141c686207d664eeba0c9 # encrypted value of your token