language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../src

script:

  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify -P test-consumer,test-business sonar:sonar -Dsonar.login=d8835cba94cdb9f3049144cdf375a880ea0f87bd
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
  - cd ../../src


notifications:
  email: false

addons:
  sonarcloud:
    organization: "kamika-ze"
    token:
      secure: d8835cba94cdb9f3049144cdf375a880ea0f87bd # encrypted value of your token